float main(float2 coords						: TEXCOORD0,
			uniform samplerRECT minTexture  	: TEXUNIT0,
			uniform samplerRECT maxTexture      : TEXUNIT1,
			uniform float4 point								) : COLOR
{
	float4 c1 = texRECT(minTexture, coords);
	float4 c2 = texRECT(maxTexture, coords);
	float4 diff1 = point-c1;
	float4 diff2 = c2-point;
	
	if (!(diff1.x>0 && diff1.y>0 && diff1.z>0 && diff2.x>0 && diff2.y>0 && diff2.z>0))
	    discard;

	return 1.0;
}