float4 main(float2 coords : TEXCOORD0,
			uniform samplerRECT surfaceTex	: TEXUNIT0,
			uniform samplerRECT normalTex	: TEXUNIT1,
			uniform float dS							) : COLOR0
{
	float4 point	= texRECT(surfaceTex,coords);
	point.xyz /= point.w;
	float4 normal	= texRECT(normalTex,coords);
	float4 moment;
	// uWeight*vWeight*momentFunction*normal[2]*surfPoint[2]*dS
	moment.x = normal.z*point.z*dS;
	moment.yzw = point.xyz*moment.x;
	moment.w *= 0.5;
	return moment;
}